export default {
    "en-US" : "English",
    "nl-NL" : "Nederlands",
    "es-ES" : "Español (ES)",
    "es-LA" : "Español (LA)",
    "fr-FR" : "Français",
    "de-DE" : "Deutsch",
    "ar-AE" : "العربية",
    "tr-TR" : "Türkçe",
    "lv-LV" : "Latviski",
    "nb-NO" : "Norsk",
    "el-GR" : "ελληνικά",
    "hi-IN" : "हिंदी",
    "id-ID" : "Bahasa Indonesia",
    "ja-JP" : "日本語",
    "pt-Pt" : "Português (PT)",
    "pt-BR" : "Português (Brasil)",
    "ro-RO" : "Română",
    "ru-RU" : "Pусский",
    "sr-CR" : "Srpski",
    "th-TH" : "ภาษาไทย",
    "vi-VN" : "Tiếng Việt",
    "zh-CN" : "简体中文",
    "it-IT" : "Italiano",
    "fi-FI" : "Suomo",
    "et-ET" : "Eesti",
    "pl-PL" : "Polski",
    "sv-SE" : "Svenska",
    "da-DK" : "Dansk",
    "cr-CR" : "Cрпски",
  
}