export default {
    "Dateline Standard Time": "(UTC-12:00) International Date Line West ",
    "Samoa Standard Time": "(UTC-11:00) Midway Island, Samoa",
    "Hawaiian Standard Time": "(UTC-10:00) Hawaii",
    "Alaskan Standard Time": "(UTC-09:00) Alaska",
    "Pacific Standard Time": "(UTC-08:00) Pacific Time (US & Canada)",
    "Pacific Standard Time (Mexico)": "(UTC-08:00) Tijuana, Baja California",
    "US Mountain Standard Time": "(UTC-07:00) Arizona",
    "Mountain Standard Time (Mexico)": "(UTC-07:00) Chihuahua, La Paz, Mazatlan",
    "Mountain Standard Time": "(UTC-07:00) Mountain Time (US & Canada)",
    "Central America Standard Time": "(UTC-06:00) Central America",
    "Central Standard Time": "(UTC-06:00) Central Time (US & Canada)",
    "Central Standard Time (Mexico)": "(UTC-06:00) Guadalajara, Mexico City, Monterrey",
    "Canada Central Standard Time": "(UTC-06:00) Saskatchewan",
    "SA Pacific Standard Time": "(UTC-05:00) Bogota, Lima, Quito",
    "Eastern Standard Time": "(UTC-05:00) Eastern Time (US & Canada)",
    "US Eastern Standard Time": "(UTC-05:00) Indiana (East)",
    "Venezuela Standard Time": "(UTC-04:30) Caracas",
    "Paraguay Standard Time": "(UTC-04:00) Asuncion",
    "Atlantic Standard Time": "(UTC-04:00) Atlantic Time (Canada)",
    "SA Western Standard Time": "(UTC-04:00) Georgetown, La Paz, San Juan",
    "Central Brazilian Standard Time": "(UTC-04:00) Manaus",
    "Pacific SA Standard Time": "(UTC-04:00) Santiago",
    "Newfoundland Standard Time": "(UTC-03:30) Newfoundland",
    "E. South America Standard Time": "(UTC-03:00) Brasilia",
    "Argentina Standard Time": "(UTC-03:00) Buenos Aires",
    "SA Eastern Standard Time": "(UTC-03:00) Cayenne",
    "Greenland Standard Time": "(UTC-03:00) Greenland",
    "Montevideo Standard Time": "(UTC-03:00) Montevideo",
    "Mid-Atlantic Standard Time": "(UTC-02:00) Mid-Atlantic",
    "Azores Standard Time": "(UTC-01:00) Azores",
    "Cabo Verde Standard Time": "(UTC-01:00) Cape Verde Is.",
    "Morocco Standard Time": "(UTC) Casablanca",
    "Coordinated Universal Time": "(UTC) Coordinated Universal Time",
    "GMT Standard Time": "(UTC) Dublin, Edinburgh, Lisbon, London",
    "Greenwich Standard Time": "(UTC) Monrovia, Reykjavik",
    "W. Europe Standard Time": "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    "Central Europe Standard Time": "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
    "Romance Standard Time": "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
    "Central European Standard Time": "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
    "W. Central Africa Standard Time": "(UTC+01:00) West Central Africa",
    "Jordan Standard Time": "(UTC+02:00) Amman",
    "GTB Standard Time": "(UTC+02:00) Athens, Bucharest, Istanbul",
    "Middle East Standard Time": "(UTC+02:00) Beirut",
    "Egypt Standard Time": "(UTC+02:00) Cairo",
    "South Africa Standard Time": "(UTC+02:00) Harare, Pretoria",
    "FLE Standard Time": "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
    "Jerusalem Standard Time": "(UTC+02:00) Jerusalem",
    "E. Europe Standard Time": "(UTC+02:00) Minsk",
    "Namibia Standard Time": "(UTC+02:00) Windhoek",
    "Arabic Standard Time": "(UTC+03:00) Baghdad",
    "Arab Standard Time": "(UTC+03:00) Kuwait, Riyadh",
    "Russia TZ 2 Standard Time": "(UTC+03:00) Moscow, St. Petersburg, Volgograd",
    "E. Africa Standard Time": "(UTC+03:00) Nairobi",
    "Russia TZ 3 Standard Time": "(UTC+04:00) Izhevsk, Samara",
    "Georgian Standard Time": "(UTC+04:00) Tbilisi",
    "Iran Standard Time": "(UTC+03:30) Tehran",
    "Arabian Standard Time": "(UTC+04:00) Abu Dhabi, Muscat",
    "Azerbaijan Standard Time": "(UTC+04:00) Baku",
    "Mauritius Standard Time": "(UTC+04:00) Port Louis",
    "Caucasus Standard Time": "(UTC+04:00) Yerevan",
    "Afghanistan Standard Time": "(UTC+04:30) Kabul",
    "Russia TZ 4 Standard Time": "(UTC+05:00) Ekaterinburg",
    "Pakistan Standard Time": "(UTC+05:00) Islamabad, Karachi",
    "West Asia Standard Time": "(UTC+05:00) Tashkent",
    "India Standard Time": "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
    "Sri Lanka Standard Time": "(UTC+05:30) Sri Jayawardenepura",
    "Nepal Standard Time": "(UTC+05:45) Kathmandu",
    "Russia TZ 5 Standard Time": "(UTC+06:00) Almaty, Novosibirsk",
    "Central Asia Standard Time": "(UTC+06:00) Astana, Dhaka",
    "Myanmar Standard Time": "(UTC+06:30) Yangon (Rangoon)",
    "SE Asia Standard Time": "(UTC+07:00) Bangkok, Hanoi, Jakarta",
    "Russia TZ 6 Standard Time": "(UTC+07:00) Krasnoyarsk",
    "China Standard Time": "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
    "Russia TZ 7 Standard Time": "(UTC+08:00) Irkutsk, Ulaan Bataar",
    "Malay Peninsula Standard Time": "(UTC+08:00) Kuala Lumpur, Singapore",
    "W. Australia Standard Time": "(UTC+08:00) Perth",
    "Taipei Standard Time": "(UTC+08:00) Taipei",
    "Tokyo Standard Time": "(UTC+09:00) Osaka, Sapporo, Tokyo",
    "Korea Standard Time": "(UTC+09:00) Seoul",
    "Russia TZ 8 Standard Time": "(UTC+09:00) Yakutsk",
    "Cen. Australia Standard Time": "(UTC+09:30) Adelaide",
    "AUS Central Standard Time": "(UTC+09:30) Darwin",
    "E. Australia Standard Time": "(UTC+10:00) Brisbane",
    "AUS Eastern Standard Time": "(UTC+10:00) Canberra, Melbourne, Sydney",
    "West Pacific Standard Time": "(UTC+10:00) Guam, Port Moresby",
    "Tasmania Standard Time": "(UTC+10:00) Hobart",
    "Russia TZ 9 Standard Time": "(UTC+10:00) Vladivostok",
    "Central Pacific Standard Time": "(UTC+11:00) Magadan, Solomon Is., New Caledonia",
    "New Zealand Standard Time": "(UTC+12:00) Auckland, Wellington",
    "Fiji Standard Time": "(UTC+12:00) Fiji, Marshall Is.",
    "Kamchatka Standard Time": "(UTC+12:00) Petropavlovsk-Kamchatsky",
    "Tonga Standard Time": "(UTC+13:00) Nuku'alofa",
    "Bahia Standard Time": "(UTC-03:00) Salvador",
    "Syria Standard Time": "(UTC+02:00) Damascus",
    "North Asia East Standard Time": "(UTC+08:00) Irkutsk, Ulaan Bataar",
    "North Asia Standard Time": "(UTC+07:00) Krasnoyarsk",
    "Magadan Standard Time": "(UTC+12:00) Magadan",
    "N. Central Asia Standard Time": "(UTC+06:00) Almaty, Novosibirsk",
    "Ulaanbaatar Standard Time": "(UTC+08:00) Ulaanbaatar",
    "Vladivostok Standard Time": "(UTC+10:00) Vladivostok",
    "Yakutsk Standard Time": "(UTC+09:00) Yakutsk",
    "Ekaterinburg Standard Time": "(UTC+05:00) Ekaterinburg",
    "Cape Verde Standard Time": "(UTC-01:00) Cape Verde Is.",
    "Russian Standard Time": "(UTC+03:00) Moscow, St. Petersburg, Volgograd",
    "Bangladesh Standard Time": "(UTC+06:00) Dhaka"
}