<template>
  <div>
    <back location="GRN - Waybill " class="mb-8" />

    <!--  Delete Modal -->
    <s-modal :modal="deleteModal">
      <div
        class="rounded bg-white px-6 py-8 font-normal"
        style="width: 400px; font-size: 14px"
      >
        <div class="flex justify-between items-center mb-5">
          <h1 class="font-semibold capitalize">Delete Item</h1>
          <img
            :src="image_close"
            alt="close"
            class="cursor-pointer"
            @click="handleClose"
          />
        </div>

        <p class="my-6">Are you sure you want to delete this item?</p>

        <s-content-seperator class="my-8" />

        <div class="flex justify-between">
          <s-button
            class="px-8 bg-light-optima-color text-primary-optima-color"
            @click="handleClose"
          >
            Cancel
          </s-button>

          <s-button class="px-8 bg-primary-optima-color text-white capitalize">
            Proceed
          </s-button>
        </div>
      </div>
    </s-modal>
    <!--  Add Supply Modal -->
    <s-modal :modal="addModal">
      <div
        class="rounded bg-white px-6 py-8 font-normal"
        style="width: 400px; font-size: 14px"
      >
        <div class="flex justify-between items-center mb-5">
          <h1 class="font-semibold capitalize">Add Item</h1>
          <img
            :src="image_close"
            alt="close"
            class="cursor-pointer"
            @click="handleClose"
          />
        </div>

        <s-combo-box class="mb-3 mt-2" />
        <s-text label="Item Name:" class="mb-3" />
        <s-text
          label="SKU:"
          placeholder="-- Autogenerated --"
          disabled
          class="mb-3"
        />
        <s-text label="UofM:" placeholder="-- Enter --" class="mb-3" />
        <s-text
          label="Batch #:"
          placeholder="-- Autogenerated --"
          disabled
          class="mb-3"
        />
        <s-text label="Expiry  Date:" type="date" class="mb-3" />
        <s-text
          label="Available Qty:"
          placeholder="-- Autogenerated --"
          disabled
          class="mb-3"
        />
        <s-text label="Delivery Qty:" placeholder="-- Enter --" class="mb-3" />

        <s-content-seperator class="my-8" />

        <div class="flex justify-between">
          <s-button
            class="px-8 bg-light-optima-color text-primary-optima-color"
            @click="handleClose"
          >
            Cancel
          </s-button>

          <s-button class="px-8 bg-primary-optima-color text-white capitalize">
            Proceed
          </s-button>
        </div>
      </div>
    </s-modal>
    <div class="bg-white px-5">
      <div class="accordion" id="accordionExample">
        <div class="accordion-item bg-white border border-gray-200">
          <h2 class="accordion-header mb-0" id="headingOne">
            <button
              class="
                accordion-button
                relative
                flex
                items-center
                w-full
                py-4
                px-5
                text-base text-black-800 text-left
                bg-white
                border-0
                rounded-none
                transition
                focus:outline-none
                semibold
              "
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#collapseOne"
              aria-expanded="true"
              aria-controls="collapseOne"
            >
              GRN Info
            </button>
          </h2>
          <div
            id="collapseOne"
            class="accordion-collapse collapse show"
            aria-labelledby="headingOne"
            data-bs-parent="#accordionExample"
          >
            <div class="accordion-body py-4 px-5">
              <div class="w-full flex">
                <div class="w-1/2 mr-2">
                  <s-text
                    label="GRN ID #:"
                    disabled
                    placeholder="-- Autoloaded --"
                  />
                </div>
                <div class="w-1/2 ml-2">
                  <s-text
                    label="Reference #:"
                    disabled
                    placeholder="-- Autoloaded --"
                  />
                </div>
              </div>
              <div class="mt-3 xl:w-96">
                <label class="form-label inline-block mb-2 text-gray-700"
                  >Description:</label
                >
                <textarea
                  class="
                    block
                    w-full
                    mt-3
                    px-3
                    py-8
                    text-base
                    border-1 border-solid border-gray-400
                    rounded
                  "
                  rows="3"
                  placeholder="-- Enter --"
                ></textarea>
              </div>
            </div>
          </div>
        </div>
        <div class="accordion-item bg-white border border-gray-200">
          <h2 class="accordion-header mb-0" id="headingTwo">
            <button
              class="
                accordion-button
                collapsed
                relative
                flex
                items-center
                w-full
                py-4
                px-5
                text-base text-gray-800 text-left
                bg-white
                border-0
                rounded-none
                transition
                focus:outline-none
              "
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#collapseTwo"
              aria-expanded="false"
              aria-controls="collapseTwo"
            >
              Receiver
            </button>
          </h2>
          <div
            id="collapseTwo"
            class="accordion-collapse collapse"
            aria-labelledby="headingTwo"
            data-bs-parent="#accordionExample"
          >
            <div class="accordion-body py-4 px-5">
              <div class="w-full flex">
                <div class="w-1/3 mr-3">
                  <s-text label="Name:" disabled />
                  <s-text label="Date:" type="date" class="my-4" />
                </div>
                <div class="w-1/3 mr-3">
                  <s-text label="Phone Number:" />
                  <s-text label="Department:" class="my-4" />
                </div>
                <div class="w-1/3">
                  <s-text label="Email:" disabled />
                  <s-select label="Receive To:" class="my-4" />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="accordion-item bg-white border border-gray-200">
          <h2 class="accordion-header mb-0" id="headingThree">
            <button
              class="
                accordion-button
                collapsed
                relative
                flex
                items-center
                w-full
                py-4
                px-5
                text-base text-gray-800 text-left
                bg-white
                border-0
                rounded-none
                transition
                focus:outline-none
              "
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#collapseThree"
              aria-expanded="false"
              aria-controls="collapseThree"
            >
              Supplier
            </button>
          </h2>
          <div
            id="collapseThree"
            class="accordion-collapse collapse"
            aria-labelledby="headingThree"
            data-bs-parent="#accordionExample"
          >
            <div class="accordion-body py-4 px-5">
              <div class="w-full flex">
                <div class="w-1/3 mr-3">
                  <p
                    class="
                      text-cloudenly-primary-main
                      flex
                      justify-end
                      whitespace-nowrap
                      cursor-pointer
                    "
                    @click="openAddModal"
                  >
                    Add New
                  </p>

                  <s-text label="Supplier Name:" />

                  <s-text label="City:" disabled class="my-4" />
                  <s-text
                    label="Apartment or House Number:"
                    disabled
                    class="my-4"
                  />
                  <s-text label="Email:" disabled class="my-4" />
                </div>
                <div class="w-1/3 mr-3 mt-4">
                  <s-text label="Country:" disabled />
                  <s-text label="Zip or Post Code:" disabled class="my-4" />
                  <s-text label="Contact Person:" disabled class="my-4" />
                </div>
                <div class="w-1/3 mt-4">
                  <s-text label="State or Region:" disabled />
                  <s-text label="Street Name:" disabled class="my-4" />
                  <s-text label="Phone Number:" disabled class="my-4" />
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="border-1 border-gray-300 w-80 border-dashed mx-6"></div>
      </div>
      <div class="my-4 py-4 px-5">
        <div class="mb-3 xl:w-96">
          <label
            for="exampleFormControlTextarea1"
            class="form-label inline-block mb-2 text-gray-700"
            >Request Description:</label
          >
          <textarea
            class="
              block
              w-full
              mt-3
              px-3
              py-8
              text-base
              border-1 border-solid border-gray-400
              rounded
            "
            rows="3"
            placeholder="-- Enter --"
          ></textarea>
        </div>
      </div>
      <div class="border-1 border-gray-300 w-80 border-dashed mx-6 mt-8"></div>
      <h1 class="px-5 py-5">Bill of Quantity</h1>
      <table class="w-full px-5">
        <thead class="px-5">
          <tr class="px-5 bg-gray-200">
            <th class="py-3">Item Name</th>
            <th>Description</th>
            <th>Sku</th>
            <th>UofM</th>
            <th>Available Quantity</th>
            <th>Qty Requested</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="n in 2" :key="n">
            <td class="border-1 border-gray-400 py-2">
              <s-text
                class="mx-4"
                placeholder="Spraying machine"
                :width="150"
              />
            </td>
            <td class="border-1 border-gray-400 py-2">
              <s-text
                class="mx-4"
                placeholder="Automatic Sprayer"
                :width="150"
              />
            </td>
            <td class="border-1 border-gray-400 py-2">
              <s-text class="mx-4" placeholder="50KG" :width="150" />
            </td>
            <td class="border-1 border-gray-400 py-2">
              <s-text class="mx-4" placeholder="nr" :width="150" />
            </td>
            <td class="border-1 border-gray-400 py-2">
              <s-text class="mx-4" placeholder="0" :width="150" />
            </td>
            <td class="border-1 border-gray-400 py-2">
              <s-text class="mx-4" placeholder="0" :width="150" />
            </td>
            <td
              class="border-1 border-gray-400 py-2 cursor-pointer"
              @click="openDeleteModal"
            >
              <img :src="trash" class="mx-6" />
            </td>
          </tr>
        </tbody>
      </table>
      <div class="py-6">
        <div class="flex justify-center cursor-pointer">
          <img :src="add" alt="" srcset="" />
          <p class="text-primary-optima-color mt-1 ml-2">Add Item</p>
        </div>
      </div>
      <div class="flex justify-between py-6">
         <div>
          <s-button class="px-8 bg-light-optima-color text-primary-optima-color">Cancel</s-button>
        </div>
        <div class="inline-flex">
          <s-button class="px-8 bg-gray-700 text-white mr-4">Save As Draft</s-button>
          <s-button class="px-8 bg-primary-optima-color text-white capitalize">Save</s-button>
        </div>
       
      </div>
    </div>
  </div>
</template>

<script>
// import { mapGetters } from "vuex";

import trash from "@/assets/images/optimaAsset/trash.svg";
import add from "@/assets/images/optimaAsset/add.svg";
import image_close from "@/assets/images/optimaAsset/shared/close-red.svg";

export default {
  data() {
    return {
      trash,
      add,
      image_close,
      deleteModal: false,
      addModal: false,
    };
  },
  methods: {
    handleClose() {
      this.deleteModal = false;
      this.addModal = false;
    },
    openDeleteModal() {
      this.deleteModal = true;
    },
    openAddModal() {
      this.addModal = true;
    },
  },
  
};
</script>
