<template>

    <div>
        <div class=" ">


            <div class="flex item-center justify-start mb-1">

                <div class=" w-1/3 mt-1">
                    <span class="">Unit of Sale (Unit)</span>
                </div>

                <div class="w-2/3 ml-10">
                    <select v-model="wholesalePriceBook.unitOfSaleUnit" name="" class="form-control  w-1/4 " id="">
                        <option v-for="(unit, index) in unitOFMeasurementData" :key="index" :value="unit.value">
                            {{unit.name}}</option>
                    </select>

                </div>
            </div>



            <div class="flex item-center justify-start mb-1">
                <div class=" w-1/3 mt-1">
                    <span class="">Unit of Sale (Pack)</span>
                </div>

                <div class="w-2/3 ml-10">
                    <select v-model="wholesalePriceBook.unitOfSalePack" name="" class="form-control  w-1/4 " id="">
                        <option v-for="(unit, index) in unitOFMeasurementData" :key="index" :value="unit.value">
                            {{unit.name}}</option>
                    </select>

                </div>
            </div>



            <div class="flex item-center justify-start mb-1">
                <div class=" w-1/3 mt-1">
                    <span>Quantity Per Pack</span>
                </div>

                <div class="w-2/3 ml-10">

                    <input @keypress="preventLetterE" @keyup="calWholesalePrice"
                        v-model="wholesalePriceBook.quantityPerPack" class="py-2  w-1/4   form-control mr-2 rounded"
                        type="number" name="" id="">

                </div>

            </div>


            <vs-divider></vs-divider>



            <div class="flex item-center justify-start mb-1">
                <div class=" w-1/3 mt-1">
                    <span>Purchase Price (Unit)</span>
                </div>

                <div class="w-2/3 flex items-center  ml-10">

                    <input @keyup="calWholesalePrice" v-model.lazy="wholesalePriceBook.purchasePriceUnit" name=""
                        v-money="money" class=" form-control w-1/4 mr-5" id="" />

                    <vs-checkbox @click="checkUseAvarageWholesale(useAverageWholesale)" v-model="useAverageWholesale">
                    </vs-checkbox>
                    <span class="text-sm text-cloudenly-primary-main"> Use avarage purchase price </span>
                </div>

            </div>



            <div class="flex item-center justify-start mb-1">
                <div class=" w-1/3 mt-1">
                    <span>Purchase Price (Pack)</span>
                </div>

                <div class="w-2/3 ml-10">
                    <input disabled v-model.lazy="wholesalePriceBook.purchasePricePack" v-money="money"
                        class="py-1 mr-2 rounded form-control w-1/4" type="text" name="" id="">

                </div>

            </div>



            <div class="flex item-center justify-start mb-1">
                <div class=" w-1/3 mt-1">
                    <span>Percentage (%) Markup</span>
                </div>

                <div class="w-2/3 ml-10 flex items-center">
                    <input @keyup="calWholesalePrice" v-model="wholesalePriceBook.percentageMarkup"
                        class="py-1 rounded form-control w-1/4" type="text" name="" id="">

                    <!-- <span v-if="getIsDiscountSetup" class=" cursor-pointer text-cloudenly-danger-main ">This is
                          value is autogenerated you can change it from your catalogue setting</span>
                        <span v-else @click="discDrawer= true" class=" cursor-pointer text-cloudenly-danger-main ">Can
                          you setup your markup rate</span> -->

                    <span class="-ml-5 mr-10">
                        %
                    </span>

                    <span @click="discDrawer= true" class="cursor-point">
                        <feather-icon icon="Edit3Icon" svgClasses="w-6 h-6 cursor-pointer text-cloudenly-primary-main ">
                        </feather-icon>
                    </span>


                </div>
            </div>

            <vs-divider></vs-divider>


            <div class="flex item-center justify-start mb-1">
                <div class=" w-1/3 mt-1">
                    <span>Recommended Wholesale Price (RRP) Per Unit</span>
                </div>

                <div class="w-2/3 ml-10">
                    <input disabled v-model.lazy="wholesalePriceBook.priceRRPUnit" v-money="money"
                        class="py-1 mr-2 rounded form-control w-1/4" type="text" name="" id="">

                </div>

            </div>


            <div class="flex item-center justify-start mb-1">
                <div class=" w-1/3 mt-1">
                    <span>Recommended Wholesale Price (RRP) Per Pack</span>
                </div>

                <div class="w-2/3 ml-10">
                    <input disabled v-model.lazy="wholesalePriceBook.priceRRPPack" v-money="money"
                        class="py-1 mr-2 rounded form-control w-1/4" type="text" name="" id="">

                </div>

            </div>

            <div class="flex item-center justify-start mb-1">
                <div class=" w-1/3 mt-1">
                    <span>Discount Limit (%)</span>
                </div>

                <div class="w-2/3 ml-10 flex items-center">
                    <input @keyup="calWholesalePrice" v-model="wholesalePriceBook.discountLimit"
                        class="py-1  rounded form-control w-1/4" type="text" name="" id="" />


                    <!-- <span v-if="getIsDiscountSetup" class=" cursor-pointer text-cloudenly-danger-main ">This is
                          value is autogenerated you can change it from your catalogue setting</span>
                        <span v-else @click="discDrawer= true" class=" cursor-pointer text-cloudenly-danger-main ">can
                          you setup your Discount Rate</span> -->

                    <span class="-ml-5 mr-10">
                        %
                    </span>

                    <span @click="discDrawer= true" class="cursor-point">
                        <feather-icon icon="Edit3Icon" svgClasses="w-6 h-6 cursor-pointer text-cloudenly-primary-main ">
                        </feather-icon>
                    </span>

                </div>
            </div>

            <hr class="mt-0 mb-0">

            <div class=" flex items-center  mt-2 ">
                <p class="font-bold text-cloudenly-primary-main">View Details of Sales Wholesale Calculation</p>
                <vs-checkbox v-model="showSalesWholesaleInfo"></vs-checkbox>
            </div>

            <!-- <vs-divider></vs-divider> -->
            <!-- Hide this Section -->
            <div v-show="showSalesWholesaleInfo">
                <div class="flex item-center justify-start mb-1">
                    <div class=" w-1/3 mt-1">
                        <span>Wholesale Price Per Unit (Less Discount)</span>
                    </div>

                    <div class="w-2/3 ml-10">
                        <input disabled v-model.lazy="wholesalePriceBook.pricePerUnitLessDiscount" v-money="money"
                            class="py-1 mr-2 rounded form-control w-1/4" type="text" name="" id="">

                    </div>

                </div>


                <div class="flex item-center justify-start mb-1">
                    <div class=" w-1/3 mt-1">
                        <span>Margin @ Discount</span>
                    </div>

                    <div class="w-2/3 ml-10">
                        <input disabled v-model.lazy="wholesalePriceBook.marginAtDiscountUnit" v-money="money"
                            class="py-1 mr-2 rounded form-control w-1/4" type="text" name="" id="">
                    </div>
                </div>


                <div class="flex item-center justify-start mb-1">
                    <div class=" w-1/3 mt-1">
                        <span> Percentage(%) Margin @ Discount</span>
                    </div>

                    <div class="w-2/3  ml-10 flex items-center">
                        <input disabled v-model="wholesalePriceBook.percentageMarginAtDiscountUnit"
                            class="py-1 mr-2 rounded form-control w-1/4" type="text" name="" id="">

                        <span class="-ml-8 ">
                            %
                        </span>

                    </div>

                </div>


                <vs-divider></vs-divider>


                <div class="flex item-center justify-start mb-1">
                    <div class=" w-1/3 mt-1">
                        <span>Wholesale Price Per Pack (Less Discount)</span>
                    </div>

                    <div class="w-2/3 ml-10">
                        <input disabled v-model.lazy="wholesalePriceBook.pricePerPackLessDiscount" v-money="money"
                            class="py-1 mr-2 rounded form-control w-1/4" type="text" name="" id="">
                    </div>
                </div>

                <div class="flex item-center justify-start mb-1">
                    <div class=" w-1/3 mt-1">
                        <span>Margin @ Discount </span>
                    </div>

                    <div class="w-2/3 ml-10">
                        <input disabled v-model.lazy="wholesalePriceBook.marginAtDiscountPack" v-money="money"
                            class="py-1 mr-2 rounded form-control w-1/4" type="text" name="" id="">
                    </div>
                </div>


                <div class="flex item-center justify-start ">
                    <div class=" w-1/3 mt-1">
                        <span> Percentage(%) Margin @ Discount</span>
                    </div>

                    <div class="w-2/3 flex items-center ml-10">
                        <input disabled v-model="wholesalePriceBook.percentageMarginAtDiscountPack"
                            class="py-1 mr-2 rounded form-control w-1/4" type="text" name="" id="">

                        <span class="-ml-8 ">
                            %
                        </span>

                    </div>
                </div>
            </div>

        </div>
    </div>
</template>

<script>
export default {

}
</script>

<style>

</style>